build-front:
  image: node:12.13-alpine
  stage: build
  script:
    - cd r3g-angular/R3GAngular
    - npm install --save three
    - npm run ng build

build-back:
  image: python:latest
  stage: build
  script:
    - cd r3g-flask
    - pip install wandb
    - pip install flask
    - wandb login 041f848335f8b0cc034a549438bfd49bd2d229e7
    - pip install pylint --upgrade
    - pylint server.py
    - pylint test.py
    - python3 test.py


