build-front:
  image: node:12.13
  stage: build
  script:
    - cd r3g-angular/R3GAngular
    - npm install --save three
    - npm run ng build

build-back:
  image: python:latest
  stage: build
  script:
    - cd r3g-flask
    - pip install wandb
    - pip install flask
    - pip install numpy
    - pip install Pillow
    - pip install matplotlib
    - wandb login
    - python3 Server.py
