wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      4: 3.7.4
      5: 0.10.14
      8:
      - 3
batchSize:
  desc: null
  value: 5
epochs:
  desc: null
  value: 4
